### ISSUE TITLE
Compile helper

### ISSUE THREAD

**Issue by danielgomezrico** [Arasthel/SwissKnife#14]
I need to add the cast to Parselable everytime that I will use it... is there any way to avoid this? 

example:
    intent.putExtra(DrawerActivity.BUNDLE_ORDER, (Parselable) actualOrder);

**Comment by eugene-kamenev** [comment]
Sure you can, take a look at [AndroidBundleDSL](/src/main/groovy/com/arasthel/swissknife/dsl/AndroidBundleDSL.groovy) class

**Comment by danielgomezrico** [comment]
the link is broken

**Comment by eugene-kamenev** [comment]
Sorry but I was from mobile, you can find it by path
24 марта 2015 г. 21:15 пользователь "Daniel" <notifications@github.com>
написал:

**Comment by eugene-kamenev** [comment]
@danielgomezrico I fixed the link, do you understand how to use these methods?

**Comment by danielgomezrico** [comment]
Thanks :+1: ! but I don't, can you some me a little example?

**Comment by eugene-kamenev** [comment]
@danielgomezrico take a look:

def map = [someKey: 'someValue', someKey2: 'someValue2'];
Bundle bundle = map.asBundle();
Bundle bundle1 = anyObject.fromMap([someKey: 'someValue', someKey2: 'someValue2']);
Bundle bundle2 = new Bundle();
bundle2.putFromMap([someKey: 'someValue', someKey2: 'someValue2']);

but it will work only for groovy classes. For Java you should explicitly use it like this:
Map bundleMap = new HashMap();
Bundle bundle1 = new Bundle();
AndroidBundleDSL.putFromMap(bundle1, bundleMap);
and so on
