### ISSUE TITLE
Could extend @Parcelable to support boolean ?

### ISSUE THREAD

**Issue by newjing** [Arasthel/SwissKnife#24]
Is there anyway I can use @ Parcelable support boolean in my class?
i.e.   automatically  handle boolean in Parcelable writeValue /readValue ?

Thanks

**Comment by eugene-kamenev** [comment]
Can you please provide an example when you cant use boolean? We tried to cover all types for @Parcelable.

**Comment by newjing** [comment]
I'm sorry. I checked Google doc and using Boolean instead of boolean works.
Thank you
