### ISSUE TITLE
Question:  How to use @Parcelable in embeded Class?

### ISSUE THREAD

**Issue by newjing** [Arasthel/SwissKnife#25]
Hi, I have two classese, A includes a list (or array/arraylist) of B, while I need to pass A as Parcelable.    A and B have NO circular dependencies.
I've tried many ways but failed. Seek for help. Thanks!
```
@ Parcelable
class A{
     .......
     List<B>   b           //also tried  B[] , not working
}
```
If I also add @ Parcelable to class B, then exception says: "ClassNotFoundException when unmarshalling: B"
If I don't do that to B, got exception  "unable to marshal value B "

What's the proper way to handle this embeded situation?

Many thanks!

**Comment by eugene-kamenev** [comment]
I think you should use ArrayList, not List interface.
11 мая 2015 г. 15:56 пользователь "newjing" <notifications@github.com>
написал:

**Comment by newjing** [comment]
Thanks , Shall I put  @ Parcelable  on class B (the embedded one)  ?

**Comment by eugene-kamenev** [comment]
@newjing yes you must use it also

**Comment by newjing** [comment]
I tried as below, still not working:
···
@Parcelable
class Game {
     ...........
     ArrayList<PhotoShow> ps = []            // also tried      ArrayList  ps

}

@Parcelable
class PhotoShow {
     ...........
}

···
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: me.android.KidFun.models.PhotoShow

Anything wrong with my usage?  Sorry for my newbie questions.

**Comment by eugene-kamenev** [comment]
Can you please fork project, modify a sample we have, provide us a link to clone and reproduce the problem to fix it. Thanks.

**Comment by newjing** [comment]
@eugene-kamenev  Thanks!

I forked this project as  " https://github.com/newjing/SwissKnife "

1. Create a Class  "Team" to include a set of existing "Person" , ArrayList type
2. Create  "ParcelableReceiveActivity"  to receive the "Team Parcelable" and display it's count
3. Reuse MainActivity "first button" click to send the Parcelable "team"  to  "ParcelableReceiveActivity"

Compiled well, after the app launches, Please click the first button, and you'll get in Logcat:

            Class not found when unmarshalling: com.dexafree.sample.Person

Please check it. Thanks!    

SwissKnife is really handy, but I met quite a few difficulties in different scenarios. I'm familiar with groovy but new to annotations. Hopefully I can at least contribute a bit as a tester. Thanks to you guys for this great work.

**Comment by eugene-kamenev** [comment]
Thank you for feedback. I'll take a look at it later.
15 мая 2015 г. 12:04 пользователь "newjing" <notifications@github.com>
написал:

**Comment by eugene-kamenev** [comment]
Ok, I see, problem exists. Will investigate.

**Comment by eugene-kamenev** [comment]
Ok, as I see from generated bytecode, it happens like this:
Team.class

```groovy
public class Team implements Parcelable, GroovyObject
{
    private static /* synthetic */ ClassInfo $staticClassInfo;
    public static Parcelable$Creator CREATOR;
    private ArrayList<Person> guys;
    private transient /* synthetic */ MetaClass metaClass;
    private String title;
    
    static {
        Team.CREATOR = (Parcelable$Creator)new Team.Creator();
    }
    
    public Team() {
        this.title = "Knife Player SuperTeam";
        this.guys = new ArrayList<Person>();
        this.metaClass = this.$getStaticMetaClass();
    }
    
    public Team(final Parcel parcel) {
        this.title = "Knife Player SuperTeam";
        this.guys = new ArrayList<Person>();
        this.metaClass = this.$getStaticMetaClass();
        final ClassLoader classLoader = Object.class.getClassLoader();
        this.title = parcel.readString();
        parcel.readList((List)this.guys, classLoader);
    }
    
    protected /* synthetic */ MetaClass $getStaticMetaClass() {
        if (this.getClass() != Team.class) {
            return ScriptBytecodeAdapter.initMetaClass((Object)this);
        }
        ClassInfo $staticClassInfo;
        if (($staticClassInfo = Team.$staticClassInfo) == null) {
            $staticClassInfo = (Team.$staticClassInfo = ClassInfo.getClassInfo((Class)this.getClass()));
        }
        return $staticClassInfo.getMetaClass();
    }
    
    public int describeContents() {
        return Integer.valueOf(0);
    }
    
    public ArrayList<Person> getGuys() {
        return this.guys;
    }
    
    public String getTitle() {
        return this.title;
    }
    
    public void setGuys(final ArrayList<Person> guys) {
        this.guys = guys;
    }
    
    public void setTitle(final String title) {
        this.title = title;
    }
    
    public void writeToParcel(final Parcel parcel, final int n) {
        parcel.writeString(this.title);
        parcel.writeList((List)this.guys);
    }
}
```

and a Person class which looks nice:

```groovy
public class Person implements Parcelable, GroovyObject
{
    private static /* synthetic */ ClassInfo $staticClassInfo;
    public static Parcelable$Creator CREATOR;
    private int age;
    private transient /* synthetic */ MetaClass metaClass;
    private String name;
    
    static {
        Person.CREATOR = (Parcelable$Creator)new Person.Creator();
    }
    
    public Person() {
        this.metaClass = this.$getStaticMetaClass();
    }
    
    public Person(final Parcel parcel) {
        this.metaClass = this.$getStaticMetaClass();
        Object.class.getClassLoader();
        this.name = parcel.readString();
        this.age = parcel.readInt();
    }
    
    public Person(final String name, final int age) {
        this.metaClass = this.$getStaticMetaClass();
        this.name = name;
        this.age = age;
    }
    
    protected /* synthetic */ MetaClass $getStaticMetaClass() {
        if (this.getClass() != Person.class) {
            return ScriptBytecodeAdapter.initMetaClass((Object)this);
        }
        ClassInfo $staticClassInfo;
        if (($staticClassInfo = Person.$staticClassInfo) == null) {
            $staticClassInfo = (Person.$staticClassInfo = ClassInfo.getClassInfo((Class)this.getClass()));
        }
        return $staticClassInfo.getMetaClass();
    }
    
    public int describeContents() {
        return Integer.valueOf(0);
    }
    
    public int getAge() {
        return this.age;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setAge(final int age) {
        this.age = age;
    }
    
    public void setName(final String name) {
        this.name = name;
    }
    
    public void writeToParcel(final Parcel parcel, final int n) {
        parcel.writeString(this.name);
        parcel.writeInt(this.age);
    }
}
```

Whats wrong here? Because of casting or what?

**Comment by eugene-kamenev** [comment]
@Arasthel can you take a look at decompiled code? Whats wrong with it?

**Comment by Arasthel** [comment]
I'm trying to find out as well.

**Comment by Arasthel** [comment]
It seems like the classloader passed to `readList` isn't the right one.

**Comment by Arasthel** [comment]
It wasn't really a matter of `@Parcelable` can't contain `@Parcelable`, but a bug with `List` reading from `Parcel`. It should be done with `parcel.readTypedList(list, MyParcelClass.CREATOR)`, while we were doing it with `parcel.readList(list)`.
