### ISSUE TITLE
Feature Request: @Argument just like @Extra

### ISSUE THREAD

**Issue by daberni** [Arasthel/SwissKnife#26]
@Argument annotation for Fragments just like the @Extra annotation for Intents

**Comment by eugene-kamenev** [comment]
Can you please describe the behavior, you want to implement.

**Comment by Arasthel** [comment]
Objects can be passed to Fragments via a Bundle named "arguments". If I'm not mistaken, you want an annotation `@Argument` which can be used to parse arguments, am I right?

**Comment by s0nerik** [comment]
The problem with this thing is that even if the AST will successfully generate the "proper fragment constructor" static method, it won't be visible in IDE, and will be highlighted as nonexistent. Seems like it can only be fixed with plugin.

**Comment by eugene-kamenev** [comment]
It can also be fixed with *.gdsl script for IDE
18 мая 2015 г. 8:44 пользователь "Alexander Isaienko" <
notifications@github.com> написал:

**Comment by daberni** [comment]
calling code
{code}
Bundle arguments = new Bundle()
arguments.putParcelable("extra", someParcelable)
Fragment fragment = new FragmentClass()
fragment.setArguments(arguments)
FragmentTransaction transaction = getFragmentManager().beginTransaction()
transaction.add(R.id.container, fragment)
{code}

{code}
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        someParcelable = arguments.getParcelable("extra")
    }
{code}
