### ISSUE TITLE
It seems that @Parcelable doesn't support Inheritance

### ISSUE THREAD

**Issue by daberni** [Arasthel/SwissKnife#28]
I have @Parcelable A, and @Parcelable B extends A

when I parcel B end unparcel it, I get an empty class B

but the same works for class A

**Comment by eugene-kamenev** [comment]
Can you please fork project, write your test case and provide a link for
us. It would be helpful.
22 мая 2015 г. 14:39 пользователь "daberni" <notifications@github.com>
написал:

**Comment by daberni** [comment]
I still have problems,
when the Parcelable is used with an Intent (putExtra, getParcelableExtra) the super-members are still not set and null

I made an fork and extended the sample project with my testcase, see
https://github.com/daberni/SwissKnife/tree/parcelable-intent
or
https://github.com/daberni/SwissKnife/commit/c74baefe54997690a6476313fe9019e22c257be0

**Comment by Arasthel** [comment]
I just did some editions on the code, as the presence of `@Parcelable` annotation wasn't checked properly - although it did somehow work on my previous tests :neutral_face: .

I'm uploading a new commit that should fix it. Please try again.

**Comment by daberni** [comment]
tested in and this works now, thank you ! :smiley:

**Comment by Arasthel** [comment]
I'll be uploading a new version soon to maven then :+1:

**Comment by daberni** [comment]
when do you plan to upload the new version?

**Comment by Arasthel** [comment]
Sorry, I still have to add the docs for the new resources annotations and I don't really have the time right now - it's being a hell of a week. I'll release everything ASAP.
