### ISSUE TITLE
java.lang.Exception: The annotated field must extends AbstractList. Type: java.util.List

### ISSUE THREAD

**Issue by AndrewReitz** [Arasthel/SwissKnife#3]
When trying to use InjectViews annotation I get the error "java.lang.Exception: The annotated field must extends AbstractList. Type: java.util.List"

Code: 
@InjectViews([R.id.main_button_do_work,  R.id.main_text]) List<View> views

**Comment by townsfolk** [comment]
I'm seeing this error in later version, not sure if I should open new one or not.

I have an Activity where I want to inject a list of views. Using `@InjectViews` seems to be causing me compilation errors stating that the field must extend `java.util.List`.
Here is the offending lines:
  
    @InjectViews([R.id.game_answer_button1, R.id.game_answer_button2, R.id.game_answer_button3, R.id.game_answer_button4])
    List<Button> answerButtons

I tried to use `List<View>` as per the examples, but that still causes me the error. Not sure what I'm doing wrong here, but simply commenting out the `@InjectViews` line fixes the problem - only no views then.

I'm using `1.3.1` version of the library.
