### ISSUE TITLE
General error during canonicalization: The annotated field must extend List. Type: java.util.List

### ISSUE THREAD

**Issue by townsfolk** [Arasthel/SwissKnife#32]
I have an Activity where I want to inject a list of views. Using `@InjectViews` seems to be causing me compilation errors stating that the field must extend `java.util.List`.
Here is the offending lines:

    @InjectViews([R.id.game_answer_button1, R.id.game_answer_button2, R.id.game_answer_button3, R.id.game_answer_button4])
    List<Button> answerButtons

I tried to use `List<View>` as per the examples, but that still causes me the error. Not sure what I'm doing wrong here, but simply commenting out the `@InjectViews` line fixes the problem - only no views then.

I'm using 1.3.1 version of the library.

This problem also happened to me in version 1.2.3, I upgraded thinking it may fix the issue.

I think this is the same error as #3, although the error is slightly different. That issue was marked fixed, so maybe this is a regression? I posted a comment there, but got no response so I decided to create a new issue, please forgive me if that was wrong.

**Comment by Arasthel** [comment]
I think I know what the bug is. `doesImplementInterface(...)` method doesn't check if the passed class *is* that interface. You wouldn't have had that problem with an `ArrayList<Button>`. I'm doing some testing, if everything's right I'll upload a fix.

**Comment by townsfolk** [comment]
ArrayList<Button> does work as a workaround until the release. Thank you for the quick turnaround!
