### ISSUE TITLE
InjectView does not find view when using platform ids

### ISSUE THREAD

**Issue by anjosc** [Arasthel/SwissKnife#39]
I had a view declared with android:id=@android:id/empty and referenced with @InjectView(android.R.id.empty) and was getting a null view.
After changing to android:id="@+id/empty" and referencing it with @InjectView(R.id.empty), I got it working.

(btw, this works with ButterKnife in regular java code)

**Comment by eugene-kamenev** [comment]
As I know SwissKnife just passes provided id to standard android find mechanism, so nothing magically happens here.

**Comment by Arasthel** [comment]
Actually, it does that in the end, but before it passes through the Finder class:

`Finder.findView(activity, "id_to_find")`

So it needs a rethinking to work with `@android` ids. I'll fix this ASAP, thank you for reporting :smile:

**Comment by jmartinesp** [comment]
It should be fixed on 1.4.0.
