### ISSUE TITLE
java.lang.IllegalArgumentException when upgrading from SwissKnife 1.2.2 to 1.4.0

### ISSUE THREAD

**Issue by ghost** [Arasthel/SwissKnife#40]
I'm using SwissKnife to develop [Phœbius](https://github.com/AugierLe42e/Phoebius), a media player project. Today, I decided to update SwissKnife from 1.2.2 to 1.4.0. While everything works well with 1.2.2, using 1.4.0 gives me the following:

```
 Caused by: java.lang.IllegalArgumentException: Binary XML file line #9: Must specify unique android:id, android:tag, or have a parent with an id for augier.fr.phoebius.UI.NavbarFragment
```

The indicated XML file is [this one](https://github.com/AugierLe42e/Phoebius/blob/develop/app/src/main/res/layout/fragment_main_page.xml).

What difference between SK 1.2.2 and SK 1.4.0 causes this behaviour?

**Comment by jmartinesp** [comment]
That doesn't seem to be related to SK at all. Please take a look at [this documentation page](http://developer.android.com/intl/es/guide/components/fragments.html#Adding), the **Note** section.

**Comment by ghost** [comment]
Maybe not. What's buzzing me is that this bug appeared only after updating SK. Anyway, I've solved this now. Thanks.
